### ISSUE TITLE
Help Request: Decreasing size of local observations

### ISSUE THREAD

**Issue by AsadJeewa** [google-deepmind/meltingpot#175]
I am working in a scaled-down version of cleanup to generate quick baselines. Please advise on how I can decrease the local observation size to be smaller than an 11x11 window

**Comment by AsadJeewa** [comment]
I was able to do this via clean_up.py config

**Comment by duenez** [comment]
For posterity, you can change the avatar view parameters: https://github.com/google-deepmind/meltingpot/blob/main/meltingpot/configs/substrates/clean_up.py#L696

However, doing so will make your agent incompatible with test scenarios. A more principled way would be to add a wrapper to your agent so that it would do this post-processing on its observations, that way it could also be placed in a scenario without problems. Something like meltingpot/utils/substrates/wrappers/base.py for a substrate at train time and an equivalent policy wrapper at test time.
